spring:
  application:
    name: Spring SAAS
  mail:
    host: localhost
app:
  security:
    allowed-endpoints:
      - "/api/auth/**"
      - "/login/oauth2/code/github/**"
      - "/actuator/**"
      - "/swagger-ui/**"
      - "/api-docs/**"
      - "/csrf"
    admin-endpoints:
      - "/api/admin/**"
    user-endpoints:
      - "/api/user/**"
springdoc:
  api-docs:
    path: /api-docs
