spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liEM0Px1eBOprz6G
            client-secret: f50e03c2568e294c64569aebfd878079b4b6645d
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    driver-class-name: org.postgresql.Driver
    username: myuser
    password: secret
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  mail:
    host: localhost
    port: 3025
    username: nathan
    password: nathan
    protocol: smtp
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          debug: true
          auth: true
          starttls:
            enable: true
      tls-enabled: true
      test-connection: false
app:
  oauth:
    redirect-uri: http://localhost:5173/auth/login
  cors:
    allowed-methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
    allowed-origins:
      - "*"
  rsa:
    rsa-private-key: classpath:certs/private.pem
    rsa-public-key: classpath:certs/public.pem
  security:
    access-token-expiration-seconds: 3600
    refresh-token-expiration-minutes: 60

logging:
  level:
    root: warn
    org.springframework.security: trace
    et.nate.backend: debug
