spring:
  application:
    name: Spring SAAS
  mail:
    host: localhost
app:
  security:
    allowed-endpoints:
      - "/api/auth/**"
      - "/login/oauth2/code/github/**"
    admin-endpoints:
      - "/api/admin/**"
    user-endpoints:
      - "/api/user/**"
